/**
 * MOCK DATASET — Nashik District, Maharashtra.
 * This file is the ONLY place geography-specific seed data lives. The app
 * architecture is region-agnostic: swap/extend this dataset (or replace the
 * services with real FastAPI calls) to cover other districts.
 * Numbers here are illustrative sample data, not official statistics.
 */
import type {
  AppNotification,
  AppUser,
  AuditLogEntry,
  Department,
  Issue,
  Region,
  WaterBody,
} from "@/types";

export const NASHIK: Region = {
  id: "nashik",
  name: "Nashik District",
  state: "Maharashtra",
  country: "India",
  center: { lat: 19.9975, lng: 73.7898 },
  defaultZoom: 10,
};

const ring = (lat: number, lng: number, r: number) =>
  Array.from({ length: 12 }, (_, i) => {
    const a = (i / 12) * Math.PI * 2;
    return { lat: +(lat + Math.sin(a) * r).toFixed(5), lng: +(lng + Math.cos(a) * r * 1.4).toFixed(5) };
  });

export const WATER_BODIES: WaterBody[] = [
  {
    id: "wb-godavari",
    name: "Godavari River",
    localName: "गोदावरी",
    type: "river",
    regionId: "nashik",
    taluka: "Nashik City",
    center: { lat: 19.9975, lng: 73.7898 },
    geometry: [
      { lat: 20.0122, lng: 73.7284 },
      { lat: 20.0041, lng: 73.7592 },
      { lat: 19.9987, lng: 73.7891 },
      { lat: 19.9834, lng: 73.8221 },
      { lat: 19.9612, lng: 73.8608 },
    ],
    lengthKm: 42,
    healthScore: 48,
    openIssues: 9,
    resolvedIssues: 21,
    lastSurveyedAt: "2026-07-18T00:00:00Z",
    description:
      "The principal river of the district, flowing through Nashik city and the Ramkund ghats. Carries heavy ritual, domestic and industrial load through the urban stretch.",
  },
  {
    id: "wb-gangapur",
    name: "Gangapur Dam",
    type: "dam",
    regionId: "nashik",
    taluka: "Nashik",
    center: { lat: 20.0186, lng: 73.6552 },
    geometry: ring(20.0186, 73.6552, 0.02),
    areaSqKm: 11.4,
    healthScore: 74,
    openIssues: 3,
    resolvedIssues: 12,
    lastSurveyedAt: "2026-07-02T00:00:00Z",
    description:
      "Primary drinking-water reservoir for Nashik city, built on the Godavari upstream of the urban stretch.",
  },
  {
    id: "wb-darna",
    name: "Darna Reservoir",
    type: "reservoir",
    regionId: "nashik",
    taluka: "Igatpuri",
    center: { lat: 19.8241, lng: 73.6712 },
    geometry: ring(19.8241, 73.6712, 0.018),
    areaSqKm: 8.2,
    healthScore: 66,
    openIssues: 4,
    resolvedIssues: 7,
    lastSurveyedAt: "2026-06-25T00:00:00Z",
    description:
      "Irrigation reservoir on the Darna river serving Igatpuri and Nashik talukas.",
  },
  {
    id: "wb-nandur",
    name: "Nandur Madhmeshwar Lake",
    type: "lake",
    regionId: "nashik",
    taluka: "Niphad",
    center: { lat: 20.0186, lng: 74.1332 },
    geometry: ring(20.0186, 74.1332, 0.015),
    areaSqKm: 10.1,
    healthScore: 71,
    openIssues: 2,
    resolvedIssues: 9,
    lastSurveyedAt: "2026-07-11T00:00:00Z",
    description:
      "Ramsar-listed wetland and bird sanctuary at the confluence of the Godavari and Kadva rivers.",
  },
  {
    id: "wb-waldevi",
    name: "Waldevi Dam",
    type: "dam",
    regionId: "nashik",
    taluka: "Nashik",
    center: { lat: 19.8908, lng: 73.7502 },
    geometry: ring(19.8908, 73.7502, 0.012),
    areaSqKm: 3.4,
    healthScore: 58,
    openIssues: 5,
    resolvedIssues: 4,
    lastSurveyedAt: "2026-05-30T00:00:00Z",
    description: "Local supply dam on the Waldevi river south of Nashik city.",
  },
  {
    id: "wb-ramkund",
    name: "Ramkund Pond",
    type: "pond",
    regionId: "nashik",
    taluka: "Nashik City",
    center: { lat: 20.0072, lng: 73.7936 },
    geometry: ring(20.0072, 73.7936, 0.004),
    areaSqKm: 0.06,
    healthScore: 39,
    openIssues: 7,
    resolvedIssues: 15,
    lastSurveyedAt: "2026-07-20T00:00:00Z",
    description:
      "Sacred bathing kund on the Godavari with very high footfall and concentrated floral and plastic waste load.",
  },
  {
    id: "wb-kadva",
    name: "Kadva River",
    type: "river",
    regionId: "nashik",
    taluka: "Dindori",
    center: { lat: 20.2011, lng: 73.8382 },
    geometry: [
      { lat: 20.2411, lng: 73.7702 },
      { lat: 20.2103, lng: 73.8112 },
      { lat: 20.1802, lng: 73.8688 },
      { lat: 20.1401, lng: 73.9302 },
    ],
    lengthKm: 38,
    healthScore: 62,
    openIssues: 3,
    resolvedIssues: 6,
    lastSurveyedAt: "2026-06-14T00:00:00Z",
    description:
      "Tributary of the Godavari running through the grape-growing belt of Dindori and Niphad.",
  },
  {
    id: "wb-chankapur",
    name: "Chankapur Dam",
    type: "dam",
    regionId: "nashik",
    taluka: "Kalwan",
    center: { lat: 20.4802, lng: 73.9202 },
    geometry: ring(20.4802, 73.9202, 0.016),
    areaSqKm: 6.1,
    healthScore: 78,
    openIssues: 1,
    resolvedIssues: 3,
    lastSurveyedAt: "2026-06-08T00:00:00Z",
    description: "Dam on the Girna river serving the Kalwan and Malegaon belt.",
  },
];

const ev = (id: string, n: string, caption: string, at: string) => ({
  id,
  url: `https://images.unsplash.com/photo-${n}?auto=format&fit=crop&w=800&q=60`,
  caption,
  capturedAt: at,
});

export const ISSUES: Issue[] = [
  {
    id: "DWG-NSK-2026-0142",
    title: "Untreated sewage inflow near Tapovan bank",
    description:
      "A open drain is discharging grey-black water directly into the river about 200 m downstream of the Tapovan footbridge. Strong smell, foam visible along the bank in the mornings.",
    category: "sewage_discharge",
    status: "in_progress",
    severity: "critical",
    waterBodyId: "wb-godavari",
    waterBodyName: "Godavari River",
    location: { lat: 20.0121, lng: 73.8154 },
    locationLabel: "Tapovan bank, Nashik City",
    reportedBy: "Anjali Deshmukh",
    reportedAt: "2026-07-28T06:40:00Z",
    updatedAt: "2026-08-09T11:20:00Z",
    evidence: [ev("e1", "1544551763-46a013bb70d5", "Drain outfall", "2026-07-28T06:38:00Z")],
    ai: {
      possibleIssue: "Untreated sewage discharge into a flowing river stretch",
      estimatedSeverity: "critical",
      possibleCause: "Possible bypass or overflow from a nearby pumping station",
      confidence: 0.82,
      reason:
        "Image shows dark grey turbid flow with surface foam at a pipe outfall, and the description mentions persistent odour — a pattern often associated with untreated domestic sewage rather than storm runoff.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-07-28T06:45:00Z",
    },
    verificationNote:
      "Site visited 29 Jul. Discharge confirmed, flow roughly 1.5 MLD by visual estimate. Photographs and GPS log attached.",
    assignedDepartment: "Nashik Municipal Corporation — Sewerage",
    actionNotes: [
      "Pumping station B-4 inspected; overflow weir found choked.",
      "Desilting crew deployed 07 Aug, temporary diversion in place.",
    ],
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Anjali Deshmukh", at: "2026-07-28T06:40:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", note: "Estimated severity: Critical (82% confidence)", at: "2026-07-28T06:45:00Z" },
      { id: "t3", stage: "under_verification", label: "Verification Requested", actor: "System", at: "2026-07-28T07:00:00Z" },
      { id: "t4", stage: "verified", label: "Verified", actor: "R. Pawar (Field Verifier)", note: "Discharge confirmed on site.", at: "2026-07-29T10:15:00Z" },
      { id: "t5", stage: "assigned", label: "Assigned", actor: "District Water Cell", note: "NMC — Sewerage", at: "2026-07-30T09:05:00Z" },
      { id: "t6", stage: "in_progress", label: "Action Initiated", actor: "NMC — Sewerage", note: "Desilting crew deployed.", at: "2026-08-07T08:30:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0139",
    title: "Floral and plastic waste accumulation at Ramkund steps",
    description:
      "Large volume of offering waste in polythene bags collecting at the north steps. Not cleared for several days.",
    category: "plastic_waste",
    status: "assigned",
    severity: "high",
    waterBodyId: "wb-ramkund",
    waterBodyName: "Ramkund Pond",
    location: { lat: 20.0074, lng: 73.7939 },
    locationLabel: "Ramkund north steps, Panchavati",
    reportedBy: "Sameer Joshi",
    reportedAt: "2026-08-02T05:10:00Z",
    updatedAt: "2026-08-08T13:00:00Z",
    evidence: [ev("e2", "1621451537084-482c73073a0f", "Waste at steps", "2026-08-02T05:08:00Z")],
    ai: {
      possibleIssue: "Solid waste accumulation from ritual offerings",
      estimatedSeverity: "high",
      possibleCause: "Insufficient collection frequency during peak footfall",
      confidence: 0.74,
      reason:
        "Visible clustered polythene and organic matter along a stepped ghat edge; typical of collection-interval gaps rather than a single dumping event.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-08-02T05:14:00Z",
    },
    verificationNote: "Confirmed 03 Aug. Roughly 40 bags along a 30 m stretch.",
    assignedDepartment: "NMC — Solid Waste Management",
    actionNotes: [],
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Sameer Joshi", at: "2026-08-02T05:10:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", note: "Estimated severity: High (74% confidence)", at: "2026-08-02T05:14:00Z" },
      { id: "t3", stage: "under_verification", label: "Verification Requested", actor: "System", at: "2026-08-02T05:30:00Z" },
      { id: "t4", stage: "verified", label: "Verified", actor: "M. Shaikh (Field Verifier)", at: "2026-08-03T09:40:00Z" },
      { id: "t5", stage: "assigned", label: "Assigned", actor: "District Water Cell", note: "NMC — Solid Waste Management", at: "2026-08-08T13:00:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0151",
    title: "Coloured effluent entering canal near Satpur MIDC",
    description:
      "Reddish-brown discharge from an unmarked pipe into the feeder canal, observed on three consecutive evenings.",
    category: "industrial_pollution",
    status: "under_verification",
    severity: "critical",
    waterBodyId: "wb-waldevi",
    waterBodyName: "Waldevi Dam",
    location: { lat: 19.9942, lng: 73.7124 },
    locationLabel: "Satpur MIDC feeder canal",
    reportedBy: "Pooja Rane",
    reportedAt: "2026-08-09T14:20:00Z",
    updatedAt: "2026-08-10T08:00:00Z",
    evidence: [ev("e3", "1611273426858-450d8e3c9fce", "Effluent outfall", "2026-08-09T14:18:00Z")],
    ai: {
      possibleIssue: "Possible untreated industrial effluent release",
      estimatedSeverity: "critical",
      possibleCause: "Possible bypass of a common effluent treatment connection",
      confidence: 0.69,
      reason:
        "Strong non-natural colouration at a discrete outfall next to an industrial estate. Colour alone cannot confirm composition — laboratory sampling is required.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-08-09T14:26:00Z",
    },
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Pooja Rane", at: "2026-08-09T14:20:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", note: "Estimated severity: Critical (69% confidence)", at: "2026-08-09T14:26:00Z" },
      { id: "t3", stage: "under_verification", label: "Verification Requested", actor: "System", at: "2026-08-09T14:40:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0148",
    title: "Construction debris dumped on Gangapur backwater edge",
    description: "Two truckloads of rubble tipped on the shoreline, narrowing the water edge.",
    category: "waste_dumping",
    status: "verified",
    severity: "medium",
    waterBodyId: "wb-gangapur",
    waterBodyName: "Gangapur Dam",
    location: { lat: 20.0231, lng: 73.6488 },
    locationLabel: "Gangapur backwaters, west edge",
    reportedBy: "Kiran More",
    reportedAt: "2026-08-05T17:05:00Z",
    updatedAt: "2026-08-07T10:00:00Z",
    evidence: [ev("e4", "1516937941344-00b4e0337589", "Debris pile", "2026-08-05T17:02:00Z")],
    ai: {
      possibleIssue: "Construction and demolition waste dumping on a shoreline",
      estimatedSeverity: "medium",
      possibleCause: "Possible unauthorised disposal by a nearby construction site",
      confidence: 0.77,
      reason:
        "Angular rubble and broken masonry piled above the waterline, consistent with tipped C&D waste rather than natural deposition.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-08-05T17:11:00Z",
    },
    verificationNote: "Confirmed; approximate volume 18 cubic metres.",
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Kiran More", at: "2026-08-05T17:05:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", at: "2026-08-05T17:11:00Z" },
      { id: "t3", stage: "under_verification", label: "Verification Requested", actor: "System", at: "2026-08-05T17:30:00Z" },
      { id: "t4", stage: "verified", label: "Verified", actor: "R. Pawar (Field Verifier)", at: "2026-08-07T10:00:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0120",
    title: "Dead fish observed along Darna shoreline",
    description: "Around 40 dead fish along a 100 m stretch after heavy rain.",
    category: "ecological_concern",
    status: "resolved",
    severity: "high",
    waterBodyId: "wb-darna",
    waterBodyName: "Darna Reservoir",
    location: { lat: 19.8288, lng: 73.6741 },
    locationLabel: "Darna east shoreline, Igatpuri",
    reportedBy: "Nilesh Bhoir",
    reportedAt: "2026-06-21T07:30:00Z",
    updatedAt: "2026-07-04T15:00:00Z",
    evidence: [ev("e5", "1439405326854-014607f694d7", "Shoreline view", "2026-06-21T07:28:00Z")],
    ai: {
      possibleIssue: "Localised fish mortality event",
      estimatedSeverity: "high",
      possibleCause: "Possible dissolved-oxygen crash following runoff inflow",
      confidence: 0.63,
      reason:
        "Mortality clustered after a rain event in a shallow shoreline zone. Toxicity cannot be ruled out without water sampling.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-06-21T07:36:00Z",
    },
    verificationNote: "Confirmed and sampled 22 Jun.",
    assignedDepartment: "MPCB — Regional Office Nashik",
    actionNotes: ["Samples collected 23 Jun.", "Carcasses cleared 25 Jun; aeration advisory issued."],
    resolutionEvidence: [ev("e6", "1470071459604-3b5ec3a7fe05", "Cleared shoreline", "2026-07-04T14:00:00Z")],
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Nilesh Bhoir", at: "2026-06-21T07:30:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", at: "2026-06-21T07:36:00Z" },
      { id: "t3", stage: "under_verification", label: "Verification Requested", actor: "System", at: "2026-06-21T08:00:00Z" },
      { id: "t4", stage: "verified", label: "Verified", actor: "M. Shaikh (Field Verifier)", at: "2026-06-22T11:00:00Z" },
      { id: "t5", stage: "assigned", label: "Assigned", actor: "District Water Cell", note: "MPCB Nashik", at: "2026-06-23T09:00:00Z" },
      { id: "t6", stage: "in_progress", label: "Action Initiated", actor: "MPCB Nashik", at: "2026-06-25T10:00:00Z" },
      { id: "t7", stage: "resolved", label: "Resolved", actor: "MPCB Nashik", note: "Shoreline cleared, advisory issued.", at: "2026-07-04T15:00:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0155",
    title: "Water hyacinth mat obstructing Kadva channel",
    description: "Dense weed mat across roughly half the channel width near the Dindori causeway.",
    category: "water_obstruction",
    status: "reported",
    severity: "medium",
    waterBodyId: "wb-kadva",
    waterBodyName: "Kadva River",
    location: { lat: 20.1998, lng: 73.8391 },
    locationLabel: "Dindori causeway",
    reportedBy: "Vaibhav Sonawane",
    reportedAt: "2026-08-11T09:15:00Z",
    updatedAt: "2026-08-11T09:20:00Z",
    evidence: [ev("e7", "1509316975850-ff9c5deb0cd9", "Weed mat", "2026-08-11T09:12:00Z")],
    ai: {
      possibleIssue: "Invasive aquatic weed growth restricting flow",
      estimatedSeverity: "medium",
      possibleCause: "Possible nutrient enrichment from agricultural runoff",
      confidence: 0.71,
      reason:
        "Uniform green surface mat across a slow-moving channel is consistent with hyacinth proliferation, which is commonly nutrient-driven.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-08-11T09:20:00Z",
    },
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Vaibhav Sonawane", at: "2026-08-11T09:15:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", at: "2026-08-11T09:20:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0133",
    title: "Encroachment on Nandur wetland buffer",
    description: "New boundary wall constructed inside the notified wetland buffer zone.",
    category: "encroachment",
    status: "rejected",
    severity: "low",
    waterBodyId: "wb-nandur",
    waterBodyName: "Nandur Madhmeshwar Lake",
    location: { lat: 20.0212, lng: 74.1388 },
    locationLabel: "Nandur Madhmeshwar buffer, Niphad",
    reportedBy: "Asha Patil",
    reportedAt: "2026-07-15T12:00:00Z",
    updatedAt: "2026-07-19T16:30:00Z",
    evidence: [ev("e8", "1500534314209-a25ddb2bd429", "Boundary wall", "2026-07-15T11:58:00Z")],
    verificationNote:
      "Site inspected 19 Jul. Structure lies outside the notified buffer as per the 2024 survey map. Closed as not an encroachment.",
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Asha Patil", at: "2026-07-15T12:00:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", at: "2026-07-15T12:06:00Z" },
      { id: "t3", stage: "under_verification", label: "Verification Requested", actor: "System", at: "2026-07-15T12:30:00Z" },
      { id: "t4", stage: "rejected", label: "Rejected", actor: "S. Kulkarni (Field Verifier)", note: "Outside notified buffer.", at: "2026-07-19T16:30:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0158",
    title: "Greywater pipe discharging into Waldevi channel",
    description: "Household greywater line routed directly into the channel behind the market lane.",
    category: "illegal_discharge",
    status: "reported",
    severity: "low",
    waterBodyId: "wb-waldevi",
    waterBodyName: "Waldevi Dam",
    location: { lat: 19.8931, lng: 73.7551 },
    locationLabel: "Waldevi channel, market lane",
    reportedBy: "Anjali Deshmukh",
    reportedAt: "2026-08-12T04:55:00Z",
    updatedAt: "2026-08-12T05:00:00Z",
    evidence: [ev("e9", "1621451537084-482c73073a0f", "Pipe outlet", "2026-08-12T04:52:00Z")],
    ai: {
      possibleIssue: "Direct greywater connection to a surface channel",
      estimatedSeverity: "low",
      possibleCause: "Possible missing household sewer connection",
      confidence: 0.58,
      reason:
        "Small-diameter pipe with intermittent clear-grey flow; volume appears low but the connection is likely unauthorised.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-08-12T05:00:00Z",
    },
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Anjali Deshmukh", at: "2026-08-12T04:55:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", at: "2026-08-12T05:00:00Z" },
    ],
  },
];

export const USERS: AppUser[] = [
  { id: "u1", name: "Anjali Deshmukh", email: "anjali.d@example.in", role: "citizen", active: true, joinedAt: "2025-11-02T00:00:00Z", reportsSubmitted: 14 },
  { id: "u2", name: "R. Pawar", email: "r.pawar@nashik.gov.example", role: "verifier", department: "District Water Cell", active: true, joinedAt: "2025-08-19T00:00:00Z" },
  { id: "u3", name: "M. Shaikh", email: "m.shaikh@nashik.gov.example", role: "verifier", department: "District Water Cell", active: true, joinedAt: "2025-09-30T00:00:00Z" },
  { id: "u4", name: "S. Kulkarni", email: "s.kulkarni@nmc.gov.example", role: "authority", department: "NMC — Sewerage", active: true, joinedAt: "2025-06-11T00:00:00Z" },
  { id: "u5", name: "District Admin", email: "admin@dwg.example", role: "admin", active: true, joinedAt: "2025-05-01T00:00:00Z" },
  { id: "u6", name: "Sameer Joshi", email: "sameer.j@example.in", role: "citizen", active: true, joinedAt: "2026-01-14T00:00:00Z", reportsSubmitted: 6 },
  { id: "u7", name: "Pooja Rane", email: "pooja.r@example.in", role: "citizen", active: false, joinedAt: "2026-02-20T00:00:00Z", reportsSubmitted: 2 },
];

export const DEPARTMENTS: Department[] = [
  { id: "d1", name: "NMC — Sewerage", contact: "sewerage@nmc.gov.example", responsibility: "Sewage networks, pumping stations, STP operations", openAssignments: 6, members: 24 },
  { id: "d2", name: "NMC — Solid Waste Management", contact: "swm@nmc.gov.example", responsibility: "Collection, ghat cleaning, C&D waste", openAssignments: 4, members: 31 },
  { id: "d3", name: "MPCB — Regional Office Nashik", contact: "nashik@mpcb.gov.example", responsibility: "Industrial effluent, sampling, enforcement", openAssignments: 3, members: 12 },
  { id: "d4", name: "Irrigation Department — Nashik", contact: "irrigation@nashik.gov.example", responsibility: "Dams, canals, reservoir shorelines", openAssignments: 2, members: 18 },
];

export const NOTIFICATIONS: AppNotification[] = [
  { id: "n1", title: "Report verified", body: "DWG-NSK-2026-0148 was verified by a field verifier.", at: "2026-08-07T10:05:00Z", read: false, kind: "status", issueId: "DWG-NSK-2026-0148" },
  { id: "n2", title: "Action initiated", body: "NMC — Sewerage has begun work on DWG-NSK-2026-0142.", at: "2026-08-07T08:35:00Z", read: false, kind: "status", issueId: "DWG-NSK-2026-0142" },
  { id: "n3", title: "Report assigned", body: "DWG-NSK-2026-0139 was assigned to NMC — Solid Waste Management.", at: "2026-08-08T13:02:00Z", read: true, kind: "assignment", issueId: "DWG-NSK-2026-0139" },
  { id: "n4", title: "AI analysis complete", body: "An assessment is available for DWG-NSK-2026-0158.", at: "2026-08-12T05:01:00Z", read: false, kind: "system", issueId: "DWG-NSK-2026-0158" },
  { id: "n5", title: "Report resolved", body: "DWG-NSK-2026-0120 was marked resolved with closure evidence.", at: "2026-07-04T15:05:00Z", read: true, kind: "status", issueId: "DWG-NSK-2026-0120" },
];

export const AUDIT_LOG: AuditLogEntry[] = [
  { id: "a1", actor: "District Admin", action: "role.assign", target: "u3 → verifier", at: "2026-08-11T10:22:00Z", ip: "10.4.2.19" },
  { id: "a2", actor: "S. Kulkarni", action: "issue.assign", target: "DWG-NSK-2026-0139", at: "2026-08-08T13:00:00Z", ip: "10.4.7.51" },
  { id: "a3", actor: "R. Pawar", action: "issue.verify", target: "DWG-NSK-2026-0148", at: "2026-08-07T10:00:00Z", ip: "10.4.7.88" },
  { id: "a4", actor: "District Admin", action: "waterbody.update", target: "wb-waldevi", at: "2026-08-05T09:12:00Z", ip: "10.4.2.19" },
  { id: "a5", actor: "System", action: "ai.triage", target: "DWG-NSK-2026-0155", at: "2026-08-11T09:20:00Z", ip: "internal" },
  { id: "a6", actor: "District Admin", action: "user.deactivate", target: "u7", at: "2026-08-03T16:40:00Z", ip: "10.4.2.19" },
];
