/**
 * MOCK DATASET — Nashik District, Maharashtra.
 * This file is the ONLY place geography-specific seed data lives. The app
 * architecture is region-agnostic: swap/extend this dataset (or replace the
 * services with real FastAPI calls) to cover other districts.
 * Numbers here are illustrative sample data, not official statistics.
 */
import type {
  AppNotification,
  AppUser,
  AuditLogEntry,
  Department,
  Issue,
  Region,
  WaterBody,
} from "@/types";

export const NASHIK: Region = {
  id: "nashik",
  name: "Nashik District",
  state: "Maharashtra",
  country: "India",
  center: { lat: 19.9975, lng: 73.7898 },
  defaultZoom: 10,
};

const ring = (lat: number, lng: number, r: number) =>
  Array.from({ length: 12 }, (_, i) => {
    const a = (i / 12) * Math.PI * 2;
    return { lat: +(lat + Math.sin(a) * r).toFixed(5), lng: +(lng + Math.cos(a) * r * 1.4).toFixed(5) };
  });

const BASE_BODIES: WaterBody[] = [
  {
    id: "wb-godavari",
    name: "Godavari River",
    localName: "गोदावरी",
    type: "river",
    regionId: "nashik",
    taluka: "Nashik City",
    center: { lat: 19.9975, lng: 73.7898 },
    geometry: [
      { lat: 20.0122, lng: 73.7284 },
      { lat: 20.0041, lng: 73.7592 },
      { lat: 19.9987, lng: 73.7891 },
      { lat: 19.9834, lng: 73.8221 },
      { lat: 19.9612, lng: 73.8608 },
    ],
    lengthKm: 42,
    healthScore: 48,
    openIssues: 9,
    resolvedIssues: 21,
    lastSurveyedAt: "2026-07-18T00:00:00Z",
    description:
      "The principal river of the district, flowing through Nashik city and the Ramkund ghats. Carries heavy ritual, domestic and industrial load through the urban stretch.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "NMC — Sewerage",
    pressures: ["Untreated sewage discharge", "Ritual and floral waste", "Encroachment on banks"],
    upstream: [{ name: "Gangapur Dam", kind: "dam" }, { name: "Kashyapi Dam", kind: "dam" }],
    downstream: [{ name: "Kadva River", kind: "confluence" }, { name: "Nandur Madhmeshwar Lake", kind: "lake" }],
    lastInspectionAt: "2026-08-01T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-gangapur",
    name: "Gangapur Dam",
    type: "dam",
    regionId: "nashik",
    taluka: "Nashik",
    center: { lat: 20.0186, lng: 73.6552 },
    geometry: ring(20.0186, 73.6552, 0.02),
    areaSqKm: 11.4,
    healthScore: 74,
    openIssues: 3,
    resolvedIssues: 12,
    lastSurveyedAt: "2026-07-02T00:00:00Z",
    description:
      "Primary drinking-water reservoir for Nashik city, built on the Godavari upstream of the urban stretch.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Backwater shoreline dumping", "Siltation"],
    upstream: [{ name: "Godavari headwaters, Trimbakeshwar", kind: "catchment" }],
    downstream: [{ name: "Godavari River", kind: "river" }],
    lastInspectionAt: "2026-07-28T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-darna",
    name: "Darna Reservoir",
    type: "reservoir",
    regionId: "nashik",
    taluka: "Igatpuri",
    center: { lat: 19.8241, lng: 73.6712 },
    geometry: ring(19.8241, 73.6712, 0.018),
    areaSqKm: 8.2,
    healthScore: 66,
    openIssues: 4,
    resolvedIssues: 7,
    lastSurveyedAt: "2026-06-25T00:00:00Z",
    description:
      "Irrigation reservoir on the Darna river serving Igatpuri and Nashik talukas.",
    riverBasin: "Darna Sub-basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Agricultural runoff", "Occasional fish mortality events"],
    upstream: [{ name: "Darna river catchment, Western Ghats", kind: "catchment" }],
    downstream: [{ name: "Godavari River", kind: "river" }],
    lastInspectionAt: "2026-07-05T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-nandur",
    name: "Nandur Madhmeshwar Lake",
    type: "lake",
    regionId: "nashik",
    taluka: "Niphad",
    center: { lat: 20.0186, lng: 74.1332 },
    geometry: ring(20.0186, 74.1332, 0.015),
    areaSqKm: 10.1,
    healthScore: 71,
    openIssues: 2,
    resolvedIssues: 9,
    lastSurveyedAt: "2026-07-11T00:00:00Z",
    description:
      "Ramsar-listed wetland and bird sanctuary at the confluence of the Godavari and Kadva rivers.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Buffer zone encroachment", "Nutrient loading from upstream agriculture"],
    upstream: [{ name: "Godavari River", kind: "river" }, { name: "Kadva River", kind: "river" }],
    downstream: [{ name: "Godavari River (downstream stretch)", kind: "river" }],
    lastInspectionAt: "2026-07-19T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-waldevi",
    name: "Waldevi Dam",
    type: "dam",
    regionId: "nashik",
    taluka: "Nashik",
    center: { lat: 19.8908, lng: 73.7502 },
    geometry: ring(19.8908, 73.7502, 0.012),
    areaSqKm: 3.4,
    healthScore: 58,
    openIssues: 5,
    resolvedIssues: 4,
    lastSurveyedAt: "2026-05-30T00:00:00Z",
    description: "Local supply dam on the Waldevi river south of Nashik city.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Industrial effluent near Satpur MIDC", "Illegal greywater connections"],
    upstream: [{ name: "Waldevi river catchment", kind: "catchment" }],
    downstream: [{ name: "Godavari River", kind: "river" }],
    lastInspectionAt: "2026-08-10T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-ramkund",
    name: "Ramkund Pond",
    type: "pond",
    regionId: "nashik",
    taluka: "Nashik City",
    center: { lat: 20.0072, lng: 73.7936 },
    geometry: ring(20.0072, 73.7936, 0.004),
    areaSqKm: 0.06,
    healthScore: 39,
    openIssues: 7,
    resolvedIssues: 15,
    lastSurveyedAt: "2026-07-20T00:00:00Z",
    description:
      "Sacred bathing kund on the Godavari with very high footfall and concentrated floral and plastic waste load.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "NMC — Solid Waste Management",
    pressures: ["Ritual and floral waste", "High pilgrim footfall", "Plastic offering bags"],
    upstream: [{ name: "Godavari River (upstream ghats)", kind: "river" }],
    downstream: [{ name: "Godavari River (downstream ghats)", kind: "river" }],
    lastInspectionAt: "2026-08-02T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-kadva",
    name: "Kadva River",
    type: "river",
    regionId: "nashik",
    taluka: "Dindori",
    center: { lat: 20.2011, lng: 73.8382 },
    geometry: [
      { lat: 20.2411, lng: 73.7702 },
      { lat: 20.2103, lng: 73.8112 },
      { lat: 20.1802, lng: 73.8688 },
      { lat: 20.1401, lng: 73.9302 },
    ],
    lengthKm: 38,
    healthScore: 62,
    openIssues: 3,
    resolvedIssues: 6,
    lastSurveyedAt: "2026-06-14T00:00:00Z",
    description:
      "Tributary of the Godavari running through the grape-growing belt of Dindori and Niphad.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Invasive water hyacinth", "Agricultural nutrient runoff"],
    upstream: [{ name: "Kadva river catchment, Dindori hills", kind: "catchment" }],
    downstream: [{ name: "Nandur Madhmeshwar Lake", kind: "lake" }],
    lastInspectionAt: "2026-06-30T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-chankapur",
    name: "Chankapur Dam",
    type: "dam",
    regionId: "nashik",
    taluka: "Kalwan",
    center: { lat: 20.4802, lng: 73.9202 },
    geometry: ring(20.4802, 73.9202, 0.016),
    areaSqKm: 6.1,
    healthScore: 78,
    openIssues: 1,
    resolvedIssues: 3,
    lastSurveyedAt: "2026-06-08T00:00:00Z",
    description: "Dam on the Girna river serving the Kalwan and Malegaon belt.",
    riverBasin: "Girna Basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Seasonal siltation", "Minor shoreline grazing pressure"],
    upstream: [{ name: "Girna river catchment, Satmala hills", kind: "catchment" }],
    downstream: [{ name: "Girna River", kind: "river" }],
    lastInspectionAt: "2026-06-20T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-mukane",
    name: "Mukane Dam",
    type: "dam",
    regionId: "nashik",
    taluka: "Igatpuri",
    center: { lat: 19.7402, lng: 73.5981 },
    geometry: ring(19.7402, 73.5981, 0.014),
    areaSqKm: 5.6,
    healthScore: 69,
    openIssues: 2,
    resolvedIssues: 5,
    lastSurveyedAt: "2026-06-16T00:00:00Z",
    description: "Dam on the Kadva river tributary in the Western Ghats near Igatpuri, feeding irrigation canals downstream.",
    riverBasin: "Kadva Sub-basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Monsoon siltation", "Occasional catchment deforestation runoff"],
    upstream: [{ name: "Western Ghats catchment, Igatpuri", kind: "catchment" }],
    downstream: [{ name: "Kadva River", kind: "river" }],
    lastInspectionAt: "2026-07-10T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-kashyapi",
    name: "Kashyapi Dam",
    type: "dam",
    regionId: "nashik",
    taluka: "Trimbakeshwar",
    center: { lat: 19.9328, lng: 73.5674 },
    geometry: ring(19.9328, 73.5674, 0.013),
    areaSqKm: 4.2,
    healthScore: 72,
    openIssues: 1,
    resolvedIssues: 4,
    lastSurveyedAt: "2026-07-06T00:00:00Z",
    description: "Supplementary drinking-water reservoir on the Kashyapi river near Trimbakeshwar, feeding into the Gangapur system.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Pilgrim-season waste near Trimbakeshwar", "Forest catchment runoff"],
    upstream: [{ name: "Kashyapi river catchment, Trimbakeshwar hills", kind: "catchment" }],
    downstream: [{ name: "Gangapur Dam", kind: "dam" }],
    lastInspectionAt: "2026-07-22T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-gautami-godavari",
    name: "Gautami Godavari Dam",
    type: "dam",
    regionId: "nashik",
    taluka: "Trimbakeshwar",
    center: { lat: 19.9481, lng: 73.5322 },
    geometry: ring(19.9481, 73.5322, 0.011),
    areaSqKm: 2.9,
    healthScore: 75,
    openIssues: 1,
    resolvedIssues: 3,
    lastSurveyedAt: "2026-06-29T00:00:00Z",
    description: "Small reservoir near the source of the Godavari at Trimbakeshwar, part of the headworks feeding the city supply network.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Headwater catchment disturbance", "Pilgrim footfall near source"],
    upstream: [{ name: "Godavari source, Brahmagiri hills", kind: "catchment" }],
    downstream: [{ name: "Gangapur Dam", kind: "dam" }],
    lastInspectionAt: "2026-07-14T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-haranbari",
    name: "Haranbari Dam",
    type: "dam",
    regionId: "nashik",
    taluka: "Baglan",
    center: { lat: 20.6124, lng: 73.9891 },
    geometry: ring(20.6124, 73.9891, 0.015),
    areaSqKm: 3.8,
    healthScore: 70,
    openIssues: 2,
    resolvedIssues: 4,
    lastSurveyedAt: "2026-06-05T00:00:00Z",
    description: "Dam on the Aram river in the Baglan taluka, supporting irrigation in the Satana belt.",
    riverBasin: "Girna Basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Agricultural runoff", "Shoreline grazing"],
    upstream: [{ name: "Aram river catchment, Baglan hills", kind: "catchment" }],
    downstream: [{ name: "Girna River", kind: "river" }],
    lastInspectionAt: "2026-06-18T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-punegaon",
    name: "Punegaon Dam",
    type: "dam",
    regionId: "nashik",
    taluka: "Baglan",
    center: { lat: 20.5691, lng: 74.0512 },
    geometry: ring(20.5691, 74.0512, 0.013),
    areaSqKm: 2.6,
    healthScore: 67,
    openIssues: 2,
    resolvedIssues: 3,
    lastSurveyedAt: "2026-05-22T00:00:00Z",
    description: "Minor irrigation dam on the Punad river serving the Satana-Malegaon agricultural belt.",
    riverBasin: "Girna Basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Sedimentation", "Pesticide-laden agricultural runoff"],
    upstream: [{ name: "Punad river catchment, Baglan", kind: "catchment" }],
    downstream: [{ name: "Girna River", kind: "river" }],
    lastInspectionAt: "2026-06-02T00:00:00Z",
    illustrative: true,
  },
  {
    id: "wb-ozarkhed",
    name: "Ozarkhed Dam",
    type: "dam",
    regionId: "nashik",
    taluka: "Dindori",
    center: { lat: 20.1842, lng: 73.9642 },
    geometry: ring(20.1842, 73.9642, 0.012),
    areaSqKm: 3.1,
    healthScore: 73,
    openIssues: 1,
    resolvedIssues: 5,
    lastSurveyedAt: "2026-07-08T00:00:00Z",
    description: "Dam on the Kadva river tributary in Dindori taluka, supporting the grape and vegetable growing belt.",
    riverBasin: "Kadva Sub-basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Fertiliser and pesticide runoff", "Minor siltation"],
    upstream: [{ name: "Kadva tributary catchment, Dindori hills", kind: "catchment" }],
    downstream: [{ name: "Kadva River", kind: "river" }],
    lastInspectionAt: "2026-07-16T00:00:00Z",
    illustrative: true,
  },
];

const line = (pts: [number, number][]) => pts.map(([lat, lng]) => ({ lat, lng }));

const APPROX = "Approximate prototype geometry — not survey-grade GeoJSON.";

/**
 * Additional records that make the dataset a connected water NETWORK rather
 * than a list of dams: a tributary river, sacred kunds, and the stream / drain
 * / canal links that carry pollution between them.
 */
const NETWORK_BODIES: WaterBody[] = [
  {
    id: "wb-darna-river",
    name: "Darna River",
    type: "tributary",
    regionId: "nashik",
    taluka: "Nashik / Igatpuri",
    center: { lat: 19.9151, lng: 73.7742 },
    geometry: line([
      [19.8298, 73.6788],
      [19.8622, 73.7042],
      [19.8951, 73.7381],
      [19.9264, 73.7822],
      [19.9531, 73.8266],
      [19.9702, 73.8688],
    ]),
    lengthKm: 34,
    healthScore: 61,
    openIssues: 3,
    resolvedIssues: 5,
    lastSurveyedAt: "2026-06-28T00:00:00Z",
    description:
      "Left-bank tributary of the Godavari, released from Darna Reservoir and joining the main stem downstream of Nashik city.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Agricultural runoff", "Sand extraction on the bed"],
    upstream: [{ name: "Darna Reservoir", kind: "reservoir" }],
    downstream: [{ name: "Godavari River", kind: "river" }],
    upstreamIds: ["wb-darna"],
    downstreamIds: ["wb-godavari"],
    lastInspectionAt: "2026-07-22T00:00:00Z",
    illustrative: true,
    featured: true,
    geometryNote: APPROX,
    condition: "fair",
  },
  {
    id: "wb-kushavart",
    name: "Kushavart Kund",
    localName: "कुशावर्त तीर्थ",
    type: "kund",
    regionId: "nashik",
    taluka: "Trimbakeshwar",
    center: { lat: 19.9328, lng: 73.5296 },
    geometry: ring(19.9328, 73.5296, 0.0022),
    areaSqKm: 0.01,
    healthScore: 44,
    openIssues: 4,
    resolvedIssues: 8,
    lastSurveyedAt: "2026-07-12T00:00:00Z",
    description:
      "Sacred kund at Trimbakeshwar, treated as the symbolic origin of the Godavari. Very high pilgrim footfall and concentrated ritual waste load.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "Trimbakeshwar Nagar Panchayat",
    pressures: ["Ritual and floral waste", "Pilgrim footfall", "Soap and oil residues"],
    upstream: [{ name: "Brahmagiri hill springs", kind: "catchment" }],
    downstream: [{ name: "Godavari River", kind: "river" }],
    downstreamIds: ["wb-godavari"],
    lastInspectionAt: "2026-08-04T00:00:00Z",
    illustrative: true,
    featured: true,
    geometryNote: APPROX,
    condition: "poor",
  },
  {
    id: "wb-tapovan-drain",
    name: "Tapovan Nalla (storm drain)",
    type: "drain",
    regionId: "nashik",
    taluka: "Nashik City",
    center: { lat: 20.0164, lng: 73.8082 },
    geometry: line([
      [20.0231, 73.7981],
      [20.0188, 73.8046],
      [20.0132, 73.8138],
      [20.0098, 73.8202],
    ]),
    lengthKm: 3.2,
    healthScore: 22,
    openIssues: 5,
    resolvedIssues: 2,
    lastSurveyedAt: "2026-08-01T00:00:00Z",
    description:
      "Urban nalla carrying mixed storm and greywater flow into the Godavari near the Tapovan bank.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "NMC — Sewerage",
    pressures: ["Illegal greywater connections", "Solid waste choking"],
    upstream: [{ name: "Panchavati ward drainage", kind: "catchment" }],
    downstream: [{ name: "Godavari River", kind: "river" }],
    downstreamIds: ["wb-godavari"],
    lastInspectionAt: "2026-08-06T00:00:00Z",
    illustrative: true,
    featured: true,
    geometryNote: APPROX,
    condition: "critical",
  },
  {
    id: "wb-dindori-stream",
    name: "Dindori feeder stream",
    type: "stream",
    regionId: "nashik",
    taluka: "Dindori",
    center: { lat: 20.2216, lng: 73.8402 },
    geometry: line([
      [20.2482, 73.8121],
      [20.2338, 73.8266],
      [20.2172, 73.8402],
      [20.2038, 73.8571],
    ]),
    lengthKm: 6.4,
    healthScore: 54,
    openIssues: 2,
    resolvedIssues: 1,
    lastSurveyedAt: "2026-06-22T00:00:00Z",
    description:
      "Seasonal stream draining vineyard and orchard land into the Kadva River.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "Zilla Parishad — Water Supply",
    pressures: ["Agricultural runoff", "Pesticide residues"],
    upstream: [{ name: "Dindori hill slopes", kind: "catchment" }],
    downstream: [{ name: "Kadva River", kind: "river" }],
    downstreamIds: ["wb-kadva"],
    lastInspectionAt: "2026-07-02T00:00:00Z",
    illustrative: true,
    featured: true,
    geometryNote: APPROX,
    condition: "fair",
  },
  {
    id: "wb-gangapur-canal",
    name: "Gangapur left-bank canal",
    type: "canal",
    regionId: "nashik",
    taluka: "Nashik",
    center: { lat: 20.0092, lng: 73.7042 },
    geometry: line([
      [20.0186, 73.6702],
      [20.0141, 73.6902],
      [20.0072, 73.7124],
      [20.0021, 73.7361],
    ]),
    lengthKm: 9.8,
    healthScore: 63,
    openIssues: 1,
    resolvedIssues: 3,
    lastSurveyedAt: "2026-06-18T00:00:00Z",
    description:
      "Irrigation canal drawing from Gangapur Reservoir towards the Satpur and Ambad belt.",
    riverBasin: "Godavari Basin",
    responsibleDepartment: "Irrigation Department — Nashik",
    pressures: ["Siltation", "Roadside dumping along the bund"],
    upstream: [{ name: "Gangapur Dam", kind: "dam" }],
    downstream: [{ name: "Waldevi Dam command area", kind: "canal" }],
    upstreamIds: ["wb-gangapur"],
    downstreamIds: ["wb-waldevi"],
    lastInspectionAt: "2026-07-08T00:00:00Z",
    illustrative: true,
    featured: true,
    geometryNote: APPROX,
    condition: "fair",
  },
];

/**
 * Default map view = the connected core network. Secondary dams stay in the
 * dataset (never deleted) but are hidden until "Show all water bodies".
 */
const FEATURED_IDS = new Set([
  "wb-gangapur",
  "wb-darna",
  "wb-godavari",
  "wb-darna-river",
  "wb-kadva",
  "wb-nandur",
  "wb-ramkund",
  "wb-kushavart",
]);

const RECLASSIFY: Record<string, Partial<WaterBody>> = {
  "wb-godavari": {
    condition: "poor",
    upstreamIds: ["wb-gangapur", "wb-kushavart"],
    downstreamIds: ["wb-ramkund", "wb-nandur"],
  },
  "wb-gangapur": {
    type: "reservoir",
    name: "Gangapur Dam & Reservoir",
    condition: "good",
    upstreamIds: ["wb-kashyapi", "wb-gautami"],
    downstreamIds: ["wb-godavari", "wb-gangapur-canal"],
  },
  "wb-darna": { condition: "fair", downstreamIds: ["wb-darna-river"] },
  "wb-nandur": {
    type: "wetland",
    name: "Nandur Madhmeshwar Wetland",
    condition: "fair",
    upstreamIds: ["wb-kadva", "wb-godavari"],
    downstreamIds: [],
  },
  "wb-ramkund": {
    type: "kund",
    name: "Ramkund",
    condition: "poor",
    upstreamIds: ["wb-godavari", "wb-tapovan-drain"],
    downstreamIds: ["wb-godavari"],
  },
  "wb-kadva": {
    type: "river",
    condition: "fair",
    upstreamIds: ["wb-dindori-stream"],
    downstreamIds: ["wb-nandur"],
  },
  "wb-waldevi": { condition: "poor" },
};

export const WATER_BODIES: WaterBody[] = [...BASE_BODIES, ...NETWORK_BODIES].map((wb) => ({
  ...wb,
  ...(RECLASSIFY[wb.id] ?? {}),
  featured: FEATURED_IDS.has(wb.id) || wb.featured === true,
  geometryNote: wb.geometryNote ?? APPROX,
}));

/**
 * Prototype connectivity traces used by "Trace Water Path".
 */
export const WATER_PATHS: { id: string; label: string; bodyIds: string[] }[] = [
  {
    id: "path-godavari-ramkund",
    label: "Kushavart → Godavari → Gangapur Reservoir → Nashik City → Ramkund",
    bodyIds: ["wb-kushavart", "wb-godavari", "wb-gangapur", "wb-tapovan-drain", "wb-ramkund"],
  },
  {
    id: "path-kadva-nandur",
    label: "Dindori stream / drain → Kadva River → Nandur Madhmeshwar → Godavari downstream",
    bodyIds: ["wb-dindori-stream", "wb-kadva", "wb-nandur", "wb-godavari"],
  },
];

const ev = (id: string, n: string, caption: string, at: string) => ({
  id,
  url: `https://images.unsplash.com/photo-${n}?auto=format&fit=crop&w=800&q=60`,
  caption,
  capturedAt: at,
});

export const ISSUES: Issue[] = [
  {
    id: "DWG-NSK-2026-0142",
    title: "Untreated sewage inflow near Tapovan bank",
    description:
      "A open drain is discharging grey-black water directly into the river about 200 m downstream of the Tapovan footbridge. Strong smell, foam visible along the bank in the mornings.",
    category: "sewage_discharge",
    status: "in_progress",
    severity: "critical",
    waterBodyId: "wb-godavari",
    waterBodyName: "Godavari River",
    location: { lat: 20.0121, lng: 73.8154 },
    locationLabel: "Tapovan bank, Nashik City",
    reportedBy: "Anjali Deshmukh",
    reportedAt: "2026-07-28T06:40:00Z",
    updatedAt: "2026-08-09T11:20:00Z",
    evidence: [ev("e1", "1544551763-46a013bb70d5", "Drain outfall", "2026-07-28T06:38:00Z")],
    ai: {
      possibleIssue: "Untreated sewage discharge into a flowing river stretch",
      estimatedSeverity: "critical",
      possibleCause: "Possible bypass or overflow from a nearby pumping station",
      confidence: 0.82,
      reason:
        "Image shows dark grey turbid flow with surface foam at a pipe outfall, and the description mentions persistent odour — a pattern often associated with untreated domestic sewage rather than storm runoff.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-07-28T06:45:00Z",
    },
    verificationNote:
      "Site visited 29 Jul. Discharge confirmed, flow roughly 1.5 MLD by visual estimate. Photographs and GPS log attached.",
    assignedDepartment: "Nashik Municipal Corporation — Sewerage",
    actionNotes: [
      "Pumping station B-4 inspected; overflow weir found choked.",
      "Desilting crew deployed 07 Aug, temporary diversion in place.",
    ],
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Anjali Deshmukh", at: "2026-07-28T06:40:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", note: "Estimated severity: Critical (82% confidence)", at: "2026-07-28T06:45:00Z" },
      { id: "t3", stage: "under_verification", label: "Verification Requested", actor: "System", at: "2026-07-28T07:00:00Z" },
      { id: "t4", stage: "verified", label: "Verified", actor: "R. Pawar (Field Verifier)", note: "Discharge confirmed on site.", at: "2026-07-29T10:15:00Z" },
      { id: "t5", stage: "assigned", label: "Assigned", actor: "District Water Cell", note: "NMC — Sewerage", at: "2026-07-30T09:05:00Z" },
      { id: "t6", stage: "in_progress", label: "Action Initiated", actor: "NMC — Sewerage", note: "Desilting crew deployed.", at: "2026-08-07T08:30:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0139",
    title: "Floral and plastic waste accumulation at Ramkund steps",
    description:
      "Large volume of offering waste in polythene bags collecting at the north steps. Not cleared for several days.",
    category: "plastic_waste",
    status: "assigned",
    severity: "high",
    waterBodyId: "wb-ramkund",
    waterBodyName: "Ramkund Pond",
    location: { lat: 20.0074, lng: 73.7939 },
    locationLabel: "Ramkund north steps, Panchavati",
    reportedBy: "Sameer Joshi",
    reportedAt: "2026-08-02T05:10:00Z",
    updatedAt: "2026-08-08T13:00:00Z",
    evidence: [ev("e2", "1621451537084-482c73073a0f", "Waste at steps", "2026-08-02T05:08:00Z")],
    ai: {
      possibleIssue: "Solid waste accumulation from ritual offerings",
      estimatedSeverity: "high",
      possibleCause: "Insufficient collection frequency during peak footfall",
      confidence: 0.74,
      reason:
        "Visible clustered polythene and organic matter along a stepped ghat edge; typical of collection-interval gaps rather than a single dumping event.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-08-02T05:14:00Z",
    },
    verificationNote: "Confirmed 03 Aug. Roughly 40 bags along a 30 m stretch.",
    assignedDepartment: "NMC — Solid Waste Management",
    actionNotes: [],
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Sameer Joshi", at: "2026-08-02T05:10:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", note: "Estimated severity: High (74% confidence)", at: "2026-08-02T05:14:00Z" },
      { id: "t3", stage: "under_verification", label: "Verification Requested", actor: "System", at: "2026-08-02T05:30:00Z" },
      { id: "t4", stage: "verified", label: "Verified", actor: "M. Shaikh (Field Verifier)", at: "2026-08-03T09:40:00Z" },
      { id: "t5", stage: "assigned", label: "Assigned", actor: "District Water Cell", note: "NMC — Solid Waste Management", at: "2026-08-08T13:00:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0151",
    title: "Coloured effluent entering canal near Satpur MIDC",
    description:
      "Reddish-brown discharge from an unmarked pipe into the feeder canal, observed on three consecutive evenings.",
    category: "industrial_pollution",
    status: "under_verification",
    severity: "critical",
    waterBodyId: "wb-waldevi",
    waterBodyName: "Waldevi Dam",
    location: { lat: 19.9942, lng: 73.7124 },
    locationLabel: "Satpur MIDC feeder canal",
    reportedBy: "Pooja Rane",
    reportedAt: "2026-08-09T14:20:00Z",
    updatedAt: "2026-08-10T08:00:00Z",
    evidence: [ev("e3", "1611273426858-450d8e3c9fce", "Effluent outfall", "2026-08-09T14:18:00Z")],
    ai: {
      possibleIssue: "Possible untreated industrial effluent release",
      estimatedSeverity: "critical",
      possibleCause: "Possible bypass of a common effluent treatment connection",
      confidence: 0.69,
      reason:
        "Strong non-natural colouration at a discrete outfall next to an industrial estate. Colour alone cannot confirm composition — laboratory sampling is required.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-08-09T14:26:00Z",
    },
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Pooja Rane", at: "2026-08-09T14:20:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", note: "Estimated severity: Critical (69% confidence)", at: "2026-08-09T14:26:00Z" },
      { id: "t3", stage: "under_verification", label: "Verification Requested", actor: "System", at: "2026-08-09T14:40:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0148",
    title: "Construction debris dumped on Gangapur backwater edge",
    description: "Two truckloads of rubble tipped on the shoreline, narrowing the water edge.",
    category: "waste_dumping",
    status: "verified",
    severity: "medium",
    waterBodyId: "wb-gangapur",
    waterBodyName: "Gangapur Dam",
    location: { lat: 20.0231, lng: 73.6488 },
    locationLabel: "Gangapur backwaters, west edge",
    reportedBy: "Kiran More",
    reportedAt: "2026-08-05T17:05:00Z",
    updatedAt: "2026-08-07T10:00:00Z",
    evidence: [ev("e4", "1516937941344-00b4e0337589", "Debris pile", "2026-08-05T17:02:00Z")],
    ai: {
      possibleIssue: "Construction and demolition waste dumping on a shoreline",
      estimatedSeverity: "medium",
      possibleCause: "Possible unauthorised disposal by a nearby construction site",
      confidence: 0.77,
      reason:
        "Angular rubble and broken masonry piled above the waterline, consistent with tipped C&D waste rather than natural deposition.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-08-05T17:11:00Z",
    },
    verificationNote: "Confirmed; approximate volume 18 cubic metres.",
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Kiran More", at: "2026-08-05T17:05:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", at: "2026-08-05T17:11:00Z" },
      { id: "t3", stage: "under_verification", label: "Verification Requested", actor: "System", at: "2026-08-05T17:30:00Z" },
      { id: "t4", stage: "verified", label: "Verified", actor: "R. Pawar (Field Verifier)", at: "2026-08-07T10:00:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0120",
    title: "Dead fish observed along Darna shoreline",
    description: "Around 40 dead fish along a 100 m stretch after heavy rain.",
    category: "ecological_concern",
    status: "resolved",
    severity: "high",
    waterBodyId: "wb-darna",
    waterBodyName: "Darna Reservoir",
    location: { lat: 19.8288, lng: 73.6741 },
    locationLabel: "Darna east shoreline, Igatpuri",
    reportedBy: "Nilesh Bhoir",
    reportedAt: "2026-06-21T07:30:00Z",
    updatedAt: "2026-07-04T15:00:00Z",
    evidence: [ev("e5", "1439405326854-014607f694d7", "Shoreline view", "2026-06-21T07:28:00Z")],
    ai: {
      possibleIssue: "Localised fish mortality event",
      estimatedSeverity: "high",
      possibleCause: "Possible dissolved-oxygen crash following runoff inflow",
      confidence: 0.63,
      reason:
        "Mortality clustered after a rain event in a shallow shoreline zone. Toxicity cannot be ruled out without water sampling.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-06-21T07:36:00Z",
    },
    verificationNote: "Confirmed and sampled 22 Jun.",
    assignedDepartment: "MPCB — Regional Office Nashik",
    actionNotes: ["Samples collected 23 Jun.", "Carcasses cleared 25 Jun; aeration advisory issued."],
    resolutionEvidence: [ev("e6", "1470071459604-3b5ec3a7fe05", "Cleared shoreline", "2026-07-04T14:00:00Z")],
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Nilesh Bhoir", at: "2026-06-21T07:30:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", at: "2026-06-21T07:36:00Z" },
      { id: "t3", stage: "under_verification", label: "Verification Requested", actor: "System", at: "2026-06-21T08:00:00Z" },
      { id: "t4", stage: "verified", label: "Verified", actor: "M. Shaikh (Field Verifier)", at: "2026-06-22T11:00:00Z" },
      { id: "t5", stage: "assigned", label: "Assigned", actor: "District Water Cell", note: "MPCB Nashik", at: "2026-06-23T09:00:00Z" },
      { id: "t6", stage: "in_progress", label: "Action Initiated", actor: "MPCB Nashik", at: "2026-06-25T10:00:00Z" },
      { id: "t7", stage: "resolved", label: "Resolved", actor: "MPCB Nashik", note: "Shoreline cleared, advisory issued.", at: "2026-07-04T15:00:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0155",
    title: "Water hyacinth mat obstructing Kadva channel",
    description: "Dense weed mat across roughly half the channel width near the Dindori causeway.",
    category: "water_obstruction",
    status: "reported",
    severity: "medium",
    waterBodyId: "wb-kadva",
    waterBodyName: "Kadva River",
    location: { lat: 20.1998, lng: 73.8391 },
    locationLabel: "Dindori causeway",
    reportedBy: "Vaibhav Sonawane",
    reportedAt: "2026-08-11T09:15:00Z",
    updatedAt: "2026-08-11T09:20:00Z",
    evidence: [ev("e7", "1509316975850-ff9c5deb0cd9", "Weed mat", "2026-08-11T09:12:00Z")],
    ai: {
      possibleIssue: "Invasive aquatic weed growth restricting flow",
      estimatedSeverity: "medium",
      possibleCause: "Possible nutrient enrichment from agricultural runoff",
      confidence: 0.71,
      reason:
        "Uniform green surface mat across a slow-moving channel is consistent with hyacinth proliferation, which is commonly nutrient-driven.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-08-11T09:20:00Z",
    },
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Vaibhav Sonawane", at: "2026-08-11T09:15:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", at: "2026-08-11T09:20:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0133",
    title: "Encroachment on Nandur wetland buffer",
    description: "New boundary wall constructed inside the notified wetland buffer zone.",
    category: "encroachment",
    status: "rejected",
    severity: "low",
    waterBodyId: "wb-nandur",
    waterBodyName: "Nandur Madhmeshwar Lake",
    location: { lat: 20.0212, lng: 74.1388 },
    locationLabel: "Nandur Madhmeshwar buffer, Niphad",
    reportedBy: "Asha Patil",
    reportedAt: "2026-07-15T12:00:00Z",
    updatedAt: "2026-07-19T16:30:00Z",
    evidence: [ev("e8", "1500534314209-a25ddb2bd429", "Boundary wall", "2026-07-15T11:58:00Z")],
    verificationNote:
      "Site inspected 19 Jul. Structure lies outside the notified buffer as per the 2024 survey map. Closed as not an encroachment.",
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Asha Patil", at: "2026-07-15T12:00:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", at: "2026-07-15T12:06:00Z" },
      { id: "t3", stage: "under_verification", label: "Verification Requested", actor: "System", at: "2026-07-15T12:30:00Z" },
      { id: "t4", stage: "rejected", label: "Rejected", actor: "S. Kulkarni (Field Verifier)", note: "Outside notified buffer.", at: "2026-07-19T16:30:00Z" },
    ],
  },
  {
    id: "DWG-NSK-2026-0158",
    title: "Greywater pipe discharging into Waldevi channel",
    description: "Household greywater line routed directly into the channel behind the market lane.",
    category: "illegal_discharge",
    status: "reported",
    severity: "low",
    waterBodyId: "wb-waldevi",
    waterBodyName: "Waldevi Dam",
    location: { lat: 19.8931, lng: 73.7551 },
    locationLabel: "Waldevi channel, market lane",
    reportedBy: "Anjali Deshmukh",
    reportedAt: "2026-08-12T04:55:00Z",
    updatedAt: "2026-08-12T05:00:00Z",
    evidence: [ev("e9", "1621451537084-482c73073a0f", "Pipe outlet", "2026-08-12T04:52:00Z")],
    ai: {
      possibleIssue: "Direct greywater connection to a surface channel",
      estimatedSeverity: "low",
      possibleCause: "Possible missing household sewer connection",
      confidence: 0.58,
      reason:
        "Small-diameter pipe with intermittent clear-grey flow; volume appears low but the connection is likely unauthorised.",
      model: "mock-vision-triage-v0",
      generatedAt: "2026-08-12T05:00:00Z",
    },
    timeline: [
      { id: "t1", stage: "reported", label: "Reported", actor: "Anjali Deshmukh", at: "2026-08-12T04:55:00Z" },
      { id: "t2", stage: "ai_analyzed", label: "AI Analyzed", actor: "Triage model", at: "2026-08-12T05:00:00Z" },
    ],
  },
];

export const USERS: AppUser[] = [
  { id: "u1", name: "Anjali Deshmukh", email: "anjali.d@example.in", role: "citizen", active: true, joinedAt: "2025-11-02T00:00:00Z", reportsSubmitted: 14 },
  { id: "u2", name: "R. Pawar", email: "r.pawar@nashik.gov.example", role: "verifier", department: "District Water Cell", active: true, joinedAt: "2025-08-19T00:00:00Z" },
  { id: "u3", name: "M. Shaikh", email: "m.shaikh@nashik.gov.example", role: "verifier", department: "District Water Cell", active: true, joinedAt: "2025-09-30T00:00:00Z" },
  { id: "u4", name: "S. Kulkarni", email: "s.kulkarni@nmc.gov.example", role: "authority", department: "NMC — Sewerage", active: true, joinedAt: "2025-06-11T00:00:00Z" },
  { id: "u5", name: "District Admin", email: "admin@dwg.example", role: "admin", active: true, joinedAt: "2025-05-01T00:00:00Z" },
  { id: "u6", name: "Sameer Joshi", email: "sameer.j@example.in", role: "citizen", active: true, joinedAt: "2026-01-14T00:00:00Z", reportsSubmitted: 6 },
  { id: "u7", name: "Pooja Rane", email: "pooja.r@example.in", role: "citizen", active: false, joinedAt: "2026-02-20T00:00:00Z", reportsSubmitted: 2 },
];

export const DEPARTMENTS: Department[] = [
  { id: "d1", name: "NMC — Sewerage", contact: "sewerage@nmc.gov.example", responsibility: "Sewage networks, pumping stations, STP operations", openAssignments: 6, members: 24, overdueAssignments: 2, resolvedAssignments: 58, medianResolutionDays: 6, slaCompliancePct: 81 },
  { id: "d2", name: "NMC — Solid Waste Management", contact: "swm@nmc.gov.example", responsibility: "Collection, ghat cleaning, C&D waste", openAssignments: 4, members: 31, overdueAssignments: 1, resolvedAssignments: 74, medianResolutionDays: 3, slaCompliancePct: 90 },
  { id: "d3", name: "MPCB — Regional Office Nashik", contact: "nashik@mpcb.gov.example", responsibility: "Industrial effluent, sampling, enforcement", openAssignments: 3, members: 12, overdueAssignments: 1, resolvedAssignments: 29, medianResolutionDays: 9, slaCompliancePct: 76 },
  { id: "d4", name: "Irrigation Department — Nashik", contact: "irrigation@nashik.gov.example", responsibility: "Dams, canals, reservoir shorelines", openAssignments: 2, members: 18, overdueAssignments: 0, resolvedAssignments: 33, medianResolutionDays: 5, slaCompliancePct: 88 },
];

export const NOTIFICATIONS: AppNotification[] = [
  { id: "n1", title: "Report verified", body: "DWG-NSK-2026-0148 was verified by a field verifier.", at: "2026-08-07T10:05:00Z", read: false, kind: "status", issueId: "DWG-NSK-2026-0148" },
  { id: "n2", title: "Action initiated", body: "NMC — Sewerage has begun work on DWG-NSK-2026-0142.", at: "2026-08-07T08:35:00Z", read: false, kind: "status", issueId: "DWG-NSK-2026-0142" },
  { id: "n3", title: "Report assigned", body: "DWG-NSK-2026-0139 was assigned to NMC — Solid Waste Management.", at: "2026-08-08T13:02:00Z", read: true, kind: "assignment", issueId: "DWG-NSK-2026-0139" },
  { id: "n4", title: "AI analysis complete", body: "An assessment is available for DWG-NSK-2026-0158.", at: "2026-08-12T05:01:00Z", read: false, kind: "system", issueId: "DWG-NSK-2026-0158" },
  { id: "n5", title: "Report resolved", body: "DWG-NSK-2026-0120 was marked resolved with closure evidence.", at: "2026-07-04T15:05:00Z", read: true, kind: "status", issueId: "DWG-NSK-2026-0120" },
];

export const AUDIT_LOG: AuditLogEntry[] = [
  { id: "a1", actor: "District Admin", action: "role.assign", target: "u3 → verifier", at: "2026-08-11T10:22:00Z", ip: "10.4.2.19" },
  { id: "a2", actor: "S. Kulkarni", action: "issue.assign", target: "DWG-NSK-2026-0139", at: "2026-08-08T13:00:00Z", ip: "10.4.7.51" },
  { id: "a3", actor: "R. Pawar", action: "issue.verify", target: "DWG-NSK-2026-0148", at: "2026-08-07T10:00:00Z", ip: "10.4.7.88" },
  { id: "a4", actor: "District Admin", action: "waterbody.update", target: "wb-waldevi", at: "2026-08-05T09:12:00Z", ip: "10.4.2.19" },
  { id: "a5", actor: "System", action: "ai.triage", target: "DWG-NSK-2026-0155", at: "2026-08-11T09:20:00Z", ip: "internal" },
  { id: "a6", actor: "District Admin", action: "user.deactivate", target: "u7", at: "2026-08-03T16:40:00Z", ip: "10.4.2.19" },
];
